language: node_js
node_js:
  - "0.12.4"
deploy:
  provider: heroku
  api_key:
    secure: b6f576d0-3f0e-424b-9833-778b0046e65d
  app: nodeapp-pi-fernanda 
  on:
    repo: feerpessoa/filipefofinho

before_script: chmod 0777 ./node_modules/.bin/mocha
